MILVUS_DEFAULT_URI = "http://localhost:19530"
MILVUS_DEFAULT_DB_NAME = "default"
DEFAULT_COLLECTION_NAME = "test_collection"
EDGE_FACE_DIM = 512
DEFAULT_VECTOR_FIELD_NAME = "embedding"
DEFAULT_METRIC = "COSINE"
